apibinanceurl=https://api.binance.com/api/v3
streambinancesocket=wss://stream.binance.com:443


# LINUX VALUES
#listsymbolfile=/home/andraina/Documents/cryptoProject/files/LIST_SYMBOL.txt
#orderFlowData=/home/andraina/Documents/cryptoProject/files/orderFlowData/
#orderBookData=/home/andraina/Documents/cryptoProject/files/orderBookData/



#WINDOWS VALUES
listsymbolfile=C:\\Users\\Andraina\\Documents\\projects\\java\\cryptoWindowsFiles\\LIST_SYMBOL.txt
orderFlowData=C:\\Users\\Andraina\\Documents\\projects\\java\\cryptoWindowsFiles\\orderFlowData\\
orderBookData=C:\\Users\\Andraina\\Documents\\projects\\java\\cryptoWindowsFiles\\orderBookData\\

